### ISSUE TITLE
Unable to get the app to run locally with docker-compose

### ISSUE THREAD

**Issue by emileten** [MAAP-Project/maap-api-nasa#102]
I followed the docker local development instructions from the README, namely : clone the repository and run from the `docker` folder `docker-compose up`. The `http://0.0.0.0:5000/` endpoint returns me nothing on the browser (dark page), and I see a couple errors in the logs returned by the `docker-compose` command (see below). 

Maybe you have an idea @bsatoriu ? Asking you since you seem to be the most active maintainer of this repository in the past couple months. Thanks ! 

```
[+] Building 0.0s (0/0)                                                                                            docker:orbstack
[+] Running 3/3
 ✔ Network docker_default   Created                                                                                           0.0s 
 ✔ Container docker-db-1    Created                                                                                           0.0s 
 ✔ Container maap-api-nasa  Created                                                                                           0.0s 
Attaching to docker-db-1, maap-api-nasa
docker-db-1    | The files belonging to this database system will be owned by user "postgres".
docker-db-1    | This user must also own the server process.
docker-db-1    | 
docker-db-1    | The database cluster will be initialized with locale "en_US.utf8".
docker-db-1    | The default database encoding has accordingly been set to "UTF8".
docker-db-1    | The default text search configuration will be set to "english".
docker-db-1    | 
docker-db-1    | Data page checksums are disabled.
docker-db-1    | 
docker-db-1    | fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
docker-db-1    | creating subdirectories ... ok
docker-db-1    | selecting dynamic shared memory implementation ... posix
docker-db-1    | selecting default max_connections ... 100
docker-db-1    | selecting default shared_buffers ... 128MB
docker-db-1    | selecting default time zone ... Etc/UTC
docker-db-1    | creating configuration files ... ok
docker-db-1    | running bootstrap script ... ok
docker-db-1    | performing post-bootstrap initialization ... ok
docker-db-1    | syncing data to disk ... ok
docker-db-1    | 
docker-db-1    | 
docker-db-1    | Success. You can now start the database server using:
docker-db-1    | 
docker-db-1    |     pg_ctl -D /var/lib/postgresql/data/pgdata -l logfile start
docker-db-1    | 
docker-db-1    | initdb: warning: enabling "trust" authentication for local connections
docker-db-1    | You can change this by editing pg_hba.conf or using the option -A, or
docker-db-1    | --auth-local and --auth-host, the next time you run initdb.
docker-db-1    | waiting for server to start....2024-03-05 13:36:44.158 UTC [49] LOG:  starting PostgreSQL 14.5 (Debian 14.5-2.pgdg110+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
docker-db-1    | 2024-03-05 13:36:44.167 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
docker-db-1    | 2024-03-05 13:36:44.169 UTC [50] LOG:  database system was shut down at 2024-03-05 13:36:43 UTC
docker-db-1    | 2024-03-05 13:36:44.174 UTC [49] LOG:  database system is ready to accept connections
docker-db-1    |  done
docker-db-1    | server started
docker-db-1    | CREATE DATABASE
docker-db-1    | 
docker-db-1    | 
docker-db-1    | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
docker-db-1    | 
docker-db-1    | 2024-03-05 13:36:44.458 UTC [49] LOG:  received fast shutdown request
docker-db-1    | waiting for server to shut down....2024-03-05 13:36:44.459 UTC [49] LOG:  aborting any active transactions
docker-db-1    | 2024-03-05 13:36:44.460 UTC [49] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
docker-db-1    | 2024-03-05 13:36:44.460 UTC [51] LOG:  shutting down
docker-db-1    | 2024-03-05 13:36:44.466 UTC [49] LOG:  database system is shut down
docker-db-1    |  done
docker-db-1    | server stopped
docker-db-1    | 
docker-db-1    | PostgreSQL init process complete; ready for start up.
docker-db-1    | 
docker-db-1    | 2024-03-05 13:36:44.575 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-2.pgdg110+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
docker-db-1    | 2024-03-05 13:36:44.575 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
docker-db-1    | 2024-03-05 13:36:44.575 UTC [1] LOG:  listening on IPv6 address "::", port 5432
docker-db-1    | 2024-03-05 13:36:44.577 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
docker-db-1    | 2024-03-05 13:36:44.580 UTC [63] LOG:  database system was shut down at 2024-03-05 13:36:44 UTC
docker-db-1    | 2024-03-05 13:36:44.585 UTC [1] LOG:  database system is ready to accept connections
maap-api-nasa  | [2024-03-05 13:36:48 +0000] [7] [INFO] Starting gunicorn 21.2.0
maap-api-nasa  | [2024-03-05 13:36:48 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
maap-api-nasa  | [2024-03-05 13:36:48 +0000] [7] [INFO] Using worker: sync
maap-api-nasa  | [2024-03-05 13:36:48 +0000] [8] [INFO] Booting worker with pid: 8
maap-api-nasa  | [2024-03-05 13:36:48 +0000] [9] [INFO] Booting worker with pid: 9
maap-api-nasa  | [2024-03-05 13:36:48 +0000] [10] [INFO] Booting worker with pid: 10
maap-api-nasa  | [2024-03-05 13:36:48 +0000] [11] [INFO] Booting worker with pid: 11
maap-api-nasa  | /maap-api-nasa/api/endpoints/job.py:65: SyntaxWarning: "is" with a literal. Did you mean "=="?
maap-api-nasa  |   queue = hysds.get_recommended_queue(job_type=job_type) if queue is None or queue is "" else queue
docker-db-1    | 2024-03-05 13:36:51.280 UTC [81] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
docker-db-1    | 2024-03-05 13:36:51.280 UTC [81] DETAIL:  Key (relname, relnamespace)=(member_id_seq, 2200) already exists.
docker-db-1    | 2024-03-05 13:36:51.280 UTC [81] STATEMENT:  
docker-db-1    |        CREATE TABLE member (
docker-db-1    |                id SERIAL NOT NULL, 
docker-db-1    |                username VARCHAR, 
docker-db-1    |                email VARCHAR, 
docker-db-1    |                first_name VARCHAR, 
docker-db-1    |                last_name VARCHAR, 
docker-db-1    |                organization VARCHAR, 
docker-db-1    |                public_ssh_key VARCHAR, 
docker-db-1    |                public_ssh_key_name VARCHAR, 
docker-db-1    |                public_ssh_key_modified_date TIMESTAMP WITHOUT TIME ZONE, 
docker-db-1    |                urs_token VARCHAR, 
docker-db-1    |                status VARCHAR, 
docker-db-1    |                gitlab_id VARCHAR, 
docker-db-1    |                gitlab_username VARCHAR, 
docker-db-1    |                gitlab_token VARCHAR, 
docker-db-1    |                creation_date TIMESTAMP WITHOUT TIME ZONE, 
docker-db-1    |                PRIMARY KEY (id), 
docker-db-1    |                UNIQUE (username), 
docker-db-1    |                UNIQUE (email)
docker-db-1    |        )
docker-db-1    | 
docker-db-1    | 
docker-db-1    | 2024-03-05 13:36:51.280 UTC [80] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
docker-db-1    | 2024-03-05 13:36:51.280 UTC [80] DETAIL:  Key (relname, relnamespace)=(member_id_seq, 2200) already exists.
docker-db-1    | 2024-03-05 13:36:51.280 UTC [80] STATEMENT:  
docker-db-1    |        CREATE TABLE member (
docker-db-1    |                id SERIAL NOT NULL, 
docker-db-1    |                username VARCHAR, 
docker-db-1    |                email VARCHAR, 
docker-db-1    |                first_name VARCHAR, 
docker-db-1    |                last_name VARCHAR, 
docker-db-1    |                organization VARCHAR, 
docker-db-1    |                public_ssh_key VARCHAR, 
docker-db-1    |                public_ssh_key_name VARCHAR, 
docker-db-1    |                public_ssh_key_modified_date TIMESTAMP WITHOUT TIME ZONE, 
docker-db-1    |                urs_token VARCHAR, 
docker-db-1    |                status VARCHAR, 
docker-db-1    |                gitlab_id VARCHAR, 
docker-db-1    |                gitlab_username VARCHAR, 
docker-db-1    |                gitlab_token VARCHAR, 
docker-db-1    |                creation_date TIMESTAMP WITHOUT TIME ZONE, 
docker-db-1    |                PRIMARY KEY (id), 
docker-db-1    |                UNIQUE (username), 
docker-db-1    |                UNIQUE (email)
docker-db-1    |        )
docker-db-1    | 
docker-db-1    | 
docker-db-1    | 2024-03-05 13:36:51.280 UTC [78] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
docker-db-1    | 2024-03-05 13:36:51.280 UTC [78] DETAIL:  Key (relname, relnamespace)=(member_id_seq, 2200) already exists.
docker-db-1    | 2024-03-05 13:36:51.280 UTC [78] STATEMENT:  
docker-db-1    |        CREATE TABLE member (
docker-db-1    |                id SERIAL NOT NULL, 
docker-db-1    |                username VARCHAR, 
docker-db-1    |                email VARCHAR, 
docker-db-1    |                first_name VARCHAR, 
docker-db-1    |                last_name VARCHAR, 
docker-db-1    |                organization VARCHAR, 
docker-db-1    |                public_ssh_key VARCHAR, 
docker-db-1    |                public_ssh_key_name VARCHAR, 
docker-db-1    |                public_ssh_key_modified_date TIMESTAMP WITHOUT TIME ZONE, 
docker-db-1    |                urs_token VARCHAR, 
docker-db-1    |                status VARCHAR, 
docker-db-1    |                gitlab_id VARCHAR, 
docker-db-1    |                gitlab_username VARCHAR, 
docker-db-1    |                gitlab_token VARCHAR, 
docker-db-1    |                creation_date TIMESTAMP WITHOUT TIME ZONE, 
docker-db-1    |                PRIMARY KEY (id), 
docker-db-1    |                UNIQUE (username), 
docker-db-1    |                UNIQUE (email)
docker-db-1    |        )
docker-db-1    | 
docker-db-1    | 
maap-api-nasa  | [2024-03-05 13:36:51 +0000] [7] [ERROR] Worker (pid:8) exited with code 3
maap-api-nasa  | [2024-03-05 13:36:51 +0000] [7] [ERROR] Worker (pid:9) exited with code 3
maap-api-nasa  | Traceback (most recent call last):
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 209, in run
maap-api-nasa  |     self.sleep()
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 360, in sleep
maap-api-nasa  |     ready = select.select([self.PIPE[0]], [], [], 1.0)
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
maap-api-nasa  |     self.reap_workers()
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
maap-api-nasa  |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
maap-api-nasa  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
maap-api-nasa  | 
maap-api-nasa  | During handling of the above exception, another exception occurred:
maap-api-nasa  | 
maap-api-nasa  | Traceback (most recent call last):
maap-api-nasa  |   File "/usr/local/bin/gunicorn", line 8, in <module>
maap-api-nasa  |     sys.exit(run())
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
maap-api-nasa  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 236, in run
maap-api-nasa  |     super().run()
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
maap-api-nasa  |     Arbiter(self).run()
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run
maap-api-nasa  |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt
maap-api-nasa  |     self.stop()
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 396, in stop
maap-api-nasa  |     time.sleep(0.1)
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
maap-api-nasa  |     self.reap_workers()
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 527, in reap_workers
maap-api-nasa  |     self.log.error('Worker (pid:%s) exited with code %s', wpid, exitcode)
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/glogging.py", line 272, in error
maap-api-nasa  |     self.error_log.error(msg, *args, **kwargs)
maap-api-nasa  |   File "/usr/local/lib/python3.9/logging/__init__.py", line 1475, in error
maap-api-nasa  |     self._log(ERROR, msg, args, **kwargs)
maap-api-nasa  |   File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
maap-api-nasa  |     self.handle(record)
maap-api-nasa  |   File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
maap-api-nasa  |     self.callHandlers(record)
maap-api-nasa  |   File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
maap-api-nasa  |     hdlr.handle(record)
maap-api-nasa  |   File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
maap-api-nasa  |     self.emit(record)
maap-api-nasa  |   File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
maap-api-nasa  |     msg = self.format(record)
maap-api-nasa  |   File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
maap-api-nasa  |     return fmt.format(record)
maap-api-nasa  |   File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
maap-api-nasa  |     record.message = record.getMessage()
maap-api-nasa  |   File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
maap-api-nasa  |     msg = msg % self.args
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
maap-api-nasa  |     self.reap_workers()
maap-api-nasa  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
maap-api-nasa  |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
maap-api-nasa  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
maap-api-nasa exited with code 1
maap-api-nasa  | [2024-03-05 13:36:51 +0000] [7] [INFO] Starting gunicorn 21.2.0
maap-api-nasa  | [2024-03-05 13:36:51 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
maap-api-nasa  | [2024-03-05 13:36:51 +0000] [7] [INFO] Using worker: sync
maap-api-nasa  | [2024-03-05 13:36:51 +0000] [8] [INFO] Booting worker with pid: 8
maap-api-nasa  | [2024-03-05 13:36:51 +0000] [9] [INFO] Booting worker with pid: 9
maap-api-nasa  | [2024-03-05 13:36:51 +0000] [10] [INFO] Booting worker with pid: 10
maap-api-nasa  | [2024-03-05 13:36:51 +0000] [11] [INFO] Booting worker with pid: 11
```

**Comment by emileten** [comment]
closing, I posted in the community page instead.
